### PR TITLE
Add 4.6.3 release

### PR DESCRIPTION
**Pull request by alexh-sauce**
Adding the 4.6.3 Sauce Connect release.

@christian-bromann

* Should I drop the 4.6.2 release?
* There are docs referring to 4.6.2 and 4.5.4, should those be updated as well?

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Let's keep 6.2. until we EOL it

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Please also update the build matrix here: https://github.com/saucelabs/sauce-connect-docker/blob/master/.github/workflows/pipeline.yml#L24

**Comment by alexh-sauce** [comment]
@christian-bromann addressed your comments, can you review?

**Review by diemol — APPROVED** [review]
Thank you, @alexh-sauce!

**Pull request merged**
