### PR TITLE
Use latest debian

### PR DESCRIPTION
**Pull request by raptorsin6**
>A customer interested in using our SC docker container ran a security scan which uncovered several vulnerabilities that need to be addressed before they are willing to use the image - issues are related to following component versions used in the image  GoLang 1.13.5 and some unbuntu 18.04.7 libraries

### CODE REVIEW

**Comment by christian-bromann** [comment]
@raptorsin6 can we remove the "4.6.5 release" commit which is already proposed in #6 ?

**Comment by raptorsin6** [comment]
> @raptorsin6 can we remove the "4.6.5 release" commit which is already proposed in #6 ?

@christian-bromann done

**Comment by christian-bromann** [comment]
> @christian-bromann done

Sorry I wasn't clear, this patch still contains changes that we have in #6. I don't mind having both in one PR but then we should close the other PR

**Comment by x7qiu** [comment]
@christian-bromann no problem. I closed the other PR.  Should we change the base branch back to the main branch?

**Comment by raptorsin6** [comment]
@christian-bromann no problem. I closed the other PR. Should we change the base branch back to the main branch?

**Review by christian-bromann — APPROVED** [review]
This looks good 👍

**Pull request merged**
